register_login_button = 'welcomeSection_auth'
enter_phone = '[class="form-control "]'
submit_button = '[class="form_submitBtn"]'
enter_code = '#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div.form_loginCode > div:nth-child(1) > span > input'
code_submit = '[type="submit"]'
google_login = 'login_google'
facebook_login = 'login_facebook.metro'
twitter_login = 'login_twitter'
no_such_user = '[class="form_message"]'
facebook_logo = '//*[@id="root"]/div/div[4]/div/div/div/div/div[3]/div[1]/span/button/img'
google_logo = '//*[@id="root"]/div/div[4]/div/div/div/div/div[3]/div[1]/button/img'
twitter_logo = '//*[@id="root"]/div/div[4]/div/div/div/div/div[3]/div[1]/div/img'
area_code = '[class ="selected-flag"]'
UK_area_code = '[data-flag-key="flag_no_2"]'
UK_flag = '[class="flag gb"]'
login_confirmation_element = '[class="login_subTitle"]'
remember_me_button = '[class="checkbox_checkboxCircle"]'
login_code_1 = '[class="input_0"]'

wrong_code_message = '[class="form_message"]'

