registration_button = '//*[@id="root"]/div/div[4]/div/div/div/div/div[1]/span[2]'
employeeID = '[label="מספר עוסק"]'
accept_terms_button = '[class="checkbox_checkboxCircle"]'
field_not_unique = '[class="form_message"]'
confirm_registration = '[type="submit"]'
insert_registration_code = '//*[@id="root"]/div/div[4]/div/div/div/div/form/div[1]/div[1]/span/input'